import { z } from 'zod';

export const DealStageEnum = z.enum(['Prospect', 'LOI', 'Negotiation', 'Executed', 'Active', 'Expired', 'Lost']);
export type DealStage = z.infer<typeof DealStageEnum>;

export const DealSchema = z.object({
  id: z.string().uuid(),
  propertyName: z.string().min(1, 'Property name is required'),
  address: z.string().default(''),
  city: z.string().default(''),
  state: z.string().default(''),
  squareFeet: z.number().int().positive().nullable().optional(),
  tenantName: z.string().min(1, 'Tenant name is required'),
  stage: DealStageEnum,
  targetCloseDate: z.string().nullable().optional(),
  broker: z.string().nullable().optional(),
  brokerCommissionPct: z.number().nullable().optional(),
  baseRentPSF: z.number().nullable().optional(),
  leaseStartDate: z.string().nullable().optional(),
  leaseEndDate: z.string().nullable().optional(),
  termMonths: z.number().int().nullable().optional(),
  rentEscalationPct: z.number().nullable().optional(),
  nnnPSF: z.number().nullable().optional(),
  tiAllowancePSF: z.number().nullable().optional(),
  freeRentMonths: z.number().int().nullable().optional(),
  renewalOptions: z.string().nullable().optional(),
  expansionRights: z.string().nullable().optional(),
  notes: z.string().nullable().optional(),
  lastModifiedBy: z.string().nullable().optional(),
  lastModifiedAt: z.string(),
}).transform((d) => ({
  ...d,
  squareFeet: d.squareFeet ?? null,
  targetCloseDate: d.targetCloseDate ?? null,
  broker: d.broker ?? null,
  brokerCommissionPct: d.brokerCommissionPct ?? null,
  baseRentPSF: d.baseRentPSF ?? null,
  leaseStartDate: d.leaseStartDate ?? null,
  leaseEndDate: d.leaseEndDate ?? null,
  termMonths: d.termMonths ?? null,
  rentEscalationPct: d.rentEscalationPct ?? null,
  nnnPSF: d.nnnPSF ?? null,
  tiAllowancePSF: d.tiAllowancePSF ?? null,
  freeRentMonths: d.freeRentMonths ?? null,
  renewalOptions: d.renewalOptions ?? null,
  expansionRights: d.expansionRights ?? null,
  notes: d.notes ?? null,
  lastModifiedBy: d.lastModifiedBy ?? null,
} as const));

export type Deal = z.infer<typeof DealSchema>;

export const defaultDeal = (): Deal => ({
  id: crypto.randomUUID(),
  propertyName: '',
  address: '',
  city: '',
  state: '',
  squareFeet: null,
  tenantName: '',
  stage: 'Prospect',
  targetCloseDate: null,
  broker: null,
  brokerCommissionPct: null,
  baseRentPSF: null,
  leaseStartDate: null,
  leaseEndDate: null,
  termMonths: null,
  rentEscalationPct: null,
  nnnPSF: null,
  tiAllowancePSF: null,
  freeRentMonths: null,
  renewalOptions: null,
  expansionRights: null,
  notes: null,
  lastModifiedBy: null,
  lastModifiedAt: new Date().toISOString(),
});
